### ISSUE TITLE
Linker error when building arm64-v8a

### ISSUE THREAD

**Issue by Meetem** [julienr/libpng-android#9] opened 2017-03-26 21:58 UTC
libpng.a(pngrutil.o): In function `png_init_filter_functions':
/home/alex/Desktop/libpng-android-master/jni/pngrutil.c:3974: undefined reference to `png_init_filter_functions_neon'

looks like this function doesn't exist for arm64, armeabi-v7a works fine

**Comment by julienr** [comment] 2017-05-25 06:56
Looks like a duplicate of #6 which was just fixed. Re-open if not

**Closed as completed by julienr** 2017-05-25 06:56 UTC
